### ISSUE TITLE
Broken Links in wiki regarding Magikarp Jump

### ISSUE THREAD

**Issue by ixanza** [pokeclicker/pokeclicker-wiki#221]
https://wiki.pokeclicker.com/#!Temporary_Battles/Magikarp%20Jump%20Koylee

Requirements portion has a link to quick league bridge in alola which links to
https://wiki.pokeclicker.com/#!Routes/Quick%20League%20Bridge%20in%20Alola which is broken

correct link currently is https://wiki.pokeclicker.com/#!Routes/Quick_League_Bridge

**Comment by CypherX** [comment]
Thanks, fixed. Might require a hard refresh for the change to show up immediately
