### ISSUE TITLE
Berries sort by farm points misbehaves

### ISSUE THREAD

**Issue by Zireael07** [pokeclicker/pokeclicker-wiki#55]
![image](https://user-images.githubusercontent.com/4525388/232490603-96006c2c-f965-4c58-a148-0aa8ddb69e23.png)

**Comment by DraKay** [comment]
Seems like it is ordering by first character and not whole number... Iirc didn't pixl fix something similar with Dungeon page?

**Comment by PixLSteam** [comment]
Yes, #15
